### ISSUE TITLE
Best practices for utilizing Bulma extensions with rbx?

### ISSUE THREAD

**Issue by stemcc** [dfee/rbx#30]
I'm curious what you would suggest the best  / least painful way to use Bulma Extensions (https://github.com/wikiki/bulma-extensions) along with rbx.

**Comment by stemcc** [comment]
Going to close this since I got it working using the integration instructions [here](https://wikiki.github.io/#integration) "From Github repository" and then adding directly to the `<Generic> `component `className="css-class-for-the-bulma-extension"`.

But please feel free to open this up again if there's a more elegant way than the above.

**Comment by davepwsmith** [comment]
I would love to know this too - I am trying to create components for Bulma Timeline (admittedly I have basically no idea what I am doing), but clearly I am doing something wrong because I keep getting errors in react like "Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports." ...

```
import classNames from 'classnames'
import * as React from 'react'

import { Generic, forwardRefAs } from 'rbx'
import { HelpersProps } from 'rbx/base/helpers'
import { TimelineHeader } from './TimelineHeader'
export type TimelineProps = HelpersProps

export const Timeline = Object.assign(
  forwardRefAs<TimelineProps>(
    ({ className, ...rest }, ref) => (
      <Generic
        className={classNames('timeline', className)}
        ref={ref}
        {...rest}
      />
    ),
    { as: 'div' }
  ),
  {
    Header: TimelineHeader,
  }
)

Timeline.displayName = 'Timeline'
```

```
import * as classNames from 'classnames'
import * as React from 'react'

import { Generic, forwardRefAs } from 'rbx'
import { HelpersProps } from 'rbx/base/helpers'

export type TimelineHeaderProps = HelpersProps

export const TimelineHeader = forwardRefAs<TimelineHeaderProps>(
  ({ className, ...rest }, ref) => (
    <Generic
      className={classNames('timeline-header', className)}
      ref={ref}
      {...rest}
    />
  ),
  {
    as: 'div',
  }
)

TimelineHeader.displayName = 'Timeline.Item'
```

**Comment by brianhiss** [comment]
@davepwsmith I'd be curious to see what you did there do get that setup and playing nice for Bulma extensions with rbx
