### ISSUE TITLE
Customization example does not work for all elements

### ISSUE THREAD

**Issue by michaelhly** [dfee/rbx#53]
Hello,

I tried out the customization instructions provided in the [docs](https://dfee.github.io/rbx/architecture/customize). However, the new `react` color works on a `notification` element but does not work on a `button` element as described in the docs.

My typescript still complains that `Type '"react"' is not assignable to type '"link" | "primary" | "success" | "info" | "warning" | "danger" | "light" | "dark" | "white" | "black" | ` as shown below: 
![Screen Shot 2019-04-04 at 12 42 54 AM](https://user-images.githubusercontent.com/24895862/55532478-ac181d00-5673-11e9-8f24-f789717f3d83.png)

Here is my react-app [setup](https://github.com/michaelhly/rbx-test). Would love to know how to get this to work properly. 

Thanks.

**Comment by michaelhly** [comment]
Follow up. Here is what my button.d.ts looks like. For some reason the `ButtonProps` are not properly overridden. 

![Screen Shot 2019-04-04 at 4 06 27 PM](https://user-images.githubusercontent.com/24895862/55588555-b24dde00-56f3-11e9-8a06-32d8b6bc0d8e.png)

**Comment by dfee** [comment]
I actually figured this out. I understand the "why" but not the "how". I've followed up on some the #typescript reactiflux channel to maybe get some more clarity here.

The background on "why" this is happening is that `tsc` isn't using `ButtonModifierProps` in `Button` upon compilation, but instead inlining the reference to "ButtonModifierProps".

Here's the skinny:
https://github.com/dfee/rbx/blob/31ba94533c9629a8201fd989b97a16d3632de725/src/elements/button/button.tsx#L30

Is compiled to:
https://gist.github.com/dfee/04cbabdf41a98c980b96ad7aa06e4e2e

Where line 17 is the proper `ButtonModifierProps` (as we'd expect it), and line 160 is the inlined `ButtonModifierProps`... not as we'd expect it.

This appears to only occur when using `Object.assign({})` on the `forwardRefAs` produced component, which is why it affects `Button` and `Tag`, but not `Notification`.

There are workarounds, but I'm going to try figure out which workaround is best.

**Comment by michaelhly** [comment]
Also (please correct me if I'm wrong), the same problem exists when setting backgroundColor for an element like `Box`.

Even though I've overridden `Variables["color"]` here
https://github.com/dfee/rbx/blob/31ba94533c9629a8201fd989b97a16d3632de725/src/base/helpers/typography.ts#L12 
Typescript will still check the default `backgroundColor` property.

Compiled box: 
https://gist.github.com/michaelhly/744a8f9b6ae0887426f4e743b46cd91b

**Comment by jazzycamel** [comment]
Having the same problem, can style a notification using my colours as described in the example, but not Button or Hero for example. Any fix imminent or a workaround I can use for now?

Thanks.

**Comment by eirikhm** [comment]
@dfee Any updates? Which workarounds did you have in mind?

**Comment by dfee** [comment]
Fixed in `next` branch, will be merged into `master` shortly.

Turns out that by using `Partial<{ ... props }>` in my declarations TS evaluated the global `Variables` during compilation (i.e. packaging, pre-distribution).

This also solves https://github.com/dfee/rbx/issues/65
