### ISSUE TITLE
this lib forces the use of "allowSyntheticDefaultImports": true

### ISSUE THREAD

**Issue by beckend** [dfee/rbx#64]
without it, tons of node_modules/@types/react/index"' has no default export.

**Comment by dfee** [comment]
In my `next` branch, I've dropped `"allowSyntheticDefaultImports:: true` from my `tsconfig.json`. However, I still have `"esModuleInterop": true` enabled. I wonder if this addresses your need?

**Comment by beckend** [comment]
Hello, everybody that currently installs this, is forced to use esModuleInterop set to true, or the tsc will not let them compile the codebase. esModuleInterop is not a default flag either.

**Comment by Retsam** [comment]
`esModuleInterop: true` implies `allowSyntheticDefaultImports: true`, so you'd have to turn that off, too.  But I think you can fix the issue without turning off synthetic default imports.

---

The issue here is that that if you look at your generated typings, a lot of them look like this:

```ts
import React from "react";

export SomeType = Whatever & React.Component</*...*/>;
```

The `import React from "react"` line is the issue: that's a synthetic default import and only works if synthetic default imports are turned on.  It's specifically an issue because that import is being preserved in the typings because they depend on `React.SomeType`.  

I believe you could fix this by going and changing `import React from "react"` to `import * as React from "react"` everywhere - but I believe you could also fix this by directly importing your types from React.  If you changed your code to be:

```ts
import React, {Component} from "react";

export SomeType = Whatever & Component</*...*/>;
```

Then your typings would compile as:

```ts
import { SomeType } from "react";

export SomeType = Whatever & Component</*...*/>
```

There's no synthetic import there, so it should work without consumers needing to turn on synthetic default imports.

**Comment by dfee** [comment]
Alright, just pushed the code to [next](https://github.com/dfee/rbx/commit/269155972e3f512cb49978f9ce17d3ba028a4312) that makes @Retsam's suggested changes. However, it seems we're outsmarted by the compiler, which ultimately just imports `import { React } from 'react'`.

You can re-produce by cloning, `npm i`, and then running `make`.

I'm unsure whether I want to proceed disabling `"esModuleInterop": true`. For instance, this doesn't seem to be a problem for [ant-design](https://github.com/ant-design/ant-design/blob/master/tsconfig.json). However, they do `import * as React from 'react';` everywhere...

Thoughts?

**Comment by beckend** [comment]
If you import the default way which is the *, then you are not using esModuleInterop anyway.

**Comment by dfee** [comment]
Ok, removed `esModuleInterop` from `tsconfig` in the `next` branch. This should now be fixed.
