### ISSUE TITLE
[Question]Button with icon having onClick issues?

### ISSUE THREAD

**Issue by tusharuclabs** [dfee/rbx#89]
When I add an icon on a Button having a text and I click on that icon while clicking the button, I cannot get the text value in _e.target.textContent_.

I get the **path of SVG** in _e.target_ but I need the text of that button.

Here is the [codeSandbox link](https://codesandbox.io/s/rbx-template-twv5t).

How do I get the value of text in button even when I click the icon in that button? Is this a bug? Or is there some other way which I am missing?

Here is the video of the issue:
![ScreenRecording2019-06-24at7](https://user-images.githubusercontent.com/51013469/60027302-db5e8900-96ba-11e9-9e1e-894c706a936f.gif)

**Comment by dfee** [comment]
A few thoughts –

1) you're not seeing the `faTwitter` icon because that's exported from `@fortawesome/free-brands-svg-icons` not `@fortawesome/free-solid-svg-icons`.

2) (if i understand correctly) you're actually trying to implement a "radio-select" or something that kinda looks like a radio form-control, but uses buttons.

If so, here's how I'd do it: https://codesandbox.io/s/rbx-button-select-xl8rl

**Comment by tusharuclabs** [comment]
> A few thoughts –
> 
> 1. you're not seeing the `faTwitter` icon because that's exported from `@fortawesome/free-brands-svg-icons` not `@fortawesome/free-solid-svg-icons`.
> 2. (if i understand correctly) you're actually trying to implement a "radio-select" or something that kinda looks like a radio form-control, but uses buttons.
> 
> If so, here's how I'd do it: https://codesandbox.io/s/rbx-button-select-xl8rl

Thanks for the reply @dfee.

1. Thanks for the icon correction.
2. Your sandbox works great for me.

Here is my problem:
I want to simply get the content(text inside the button) by using `e.target.textContent`. Shouldn't I get this value by clicking anywhere on the button? Even if I click on the icon inside this button?

Here is a [codesandbox example](https://codesandbox.io/s/romantic-wright-03yi7) where the icon is added in the HTML button using CSS. Here my above scenario works fine.

**Comment by dfee** [comment]
Try using `e.currentTarget` instead of `e.target`. Here's a [demo sandbox](https://codesandbox.io/s/rbx-89-5xdny) that replicates your second example.

You might also find this [medium article](https://medium.com/@florenceliang/javascript-event-delegation-and-event-target-vs-event-currenttarget-c9680c3a46d1) informative!

Specifically:

> Again, the currentTarget refers to the element that the event listener directly attached to while the target still refers to the specific <a> we clicked.

Let me know if we should re-open.

**Comment by tusharuclabs** [comment]
@dfee, this works great. Thanks and cheers for making such an awesome library!
